### ISSUE TITLE
Very Impressive

### ISSUE THREAD

**Issue by samehhady** [aplikatika/Espruino-on-ESP8266#1]
Hi Aplikatika,

You don't know how much I appreciate what you are doing so far in implementing Esprino directly on ESP, I've been searching forever for this!

Please tell me it is possible to do it, also you think its possible to have file based system and save javascript code there? something like lua using spiffs? in that case we can just upload the js code and it would run directly!

I would love to test with you if possible.

**Comment by aplikatika** [comment]
Hi @samehhady!

First, thank you for your feedback and support! I am glad that someone is tracking the progress of this project. I will definitely need a help with testing and will be very happy if you report some issues. It would be also nice I get some help in development.

I actually succeeded with compiling, linking, flashing and running the code. You can try it yourself by downloading binaries from /firmware/. Note that binary 0x10000.bin should be flashed to address 0x10000 (I am sure you already know that). Very soon I will make a possibility to send JS code via serial port, so that way it will be very easy to test.

I am not sure but I think Espruino already has a file system implemented, so I will only need to implement functions for writing and reading from flash memory. If not, then I will try to use Heatshrink from Scott Vokes, like it is used in github.com/bjpirt/esphttpd or maybe spiffs as you mentioned but I don't know this one yet.

Please keep in touch!

Blaž

**Comment by samehhady** [comment]
Hi Blaz,

Thank you for the info.

I have managed to build the project after some modifications
Mainly i had to comment out all stdint.h includes as many errors related to it.
Also I've added this flag -Wno-error=strict-aliasing to the makefile cause i had error related to flags which stopped the build.
and the last part was replacing #include <inttypes.h> with #include <c_types.h> in sha1.h to prevent build errors related to duplicate types.

What I've noticed is that my generated bins are smaller than yours while it is working properly!

So mine are 48 & 260kb  while yours are 49 & 276kb.

I can see the return properly once the ESP boot ( Espruino logo etc. )

I've also tried adding function in console & doing basic operations like 1+3 etc and all worked great!

Great work so far, we need now to save this code and not just print it & use espruino init function.

It would be great also to start defining the ESP gpio pins to be able to test it.

Great work Blaz! I am here to test with you all kind of stuff :)

**Comment by samehhady** [comment]
I really want to help but I am not a C guy, I am a web developer & more focused on JavaScript and thats why i am in love with Espruino.

Still I am aware of Espressif api and can help in implementing the functions if you provided me with a starting point. I've been searching the code on how the functions are actually called and how to link something like digitalWrite() in javascript to the real C code but no lock so far.

**Comment by aplikatika** [comment]
Hi @samehhady!

Sorry for my late reply, I spent all time on coding yesterday... You might have noticed I implemented gpio, so we can play with LEDs now :)

Pins are mapped as:
0 = GPIO0
1 = U0TXD / GPIO1
2 = GPIO2 / U1TXD_BK / U0TXD_BK
3 = U0RXD / GPIO3
4 = GPIO4
5 = GPIO5
6 = SDCLK / SPICLK
7 = SDDATA0 / SPIQ / U1TXD
8 = SDDATA1 / SPID / U1RXD / U1RXD
9 = SDDATA2 / SPIHD / GPIO9
10 = SDDATA3 / SPIWP / GPIO10
11 = SDCMD / SPICS0
12 = MTDI / GPIO12
13 = MTCK / GPIO13
14 = MTMS / GPIO14
15 = MTDO / GPIO15 / U0RTS

Example - toggle gpio2:
var gpio2 = new Pin(2);
gpio2.write(!gpio2.read());

Great that you managed to build the project, I did all your modifications and it builds for me as well. The -Wno-error=strict-aliasing is for CFLAGS, right?

No problem if you are not C/C++ guy, since you may help in so many different ways. Are you also familiar with python? If so, I think you might prepare scripts for the ESP boards for espruino/Espruino repository. Otherwise please wait few more days so I implement a simple FS for running JS scripts. I think I will simplify it for now by uploading a single .js file with esptool straight to flash (i.e. address 0x60000). Anyway you may do any changes here and send a pull request, I will accept all your updates.

If you use Skype, please send a contact to my email (it should be published here in github), so we will communicate easier.

**Comment by aplikatika** [comment]
Well, you don't need to wait a few days for running JS from flash, because it is done! ;) Next I will clean debug prints (actually refactor user_main), so it will not be so confusing. Please see my issue #2 if you can help...

**Comment by samehhady** [comment]
Hi Blaz,

Great work!, I will test it out today once I am back home and will share with you my findings.
Also for the makefile I will look at it, it should be simple.

My Skype is sameh.hady

Thank you again for your great work :)

**Comment by heri16** [comment]
How can I help in the effort?

**Comment by aplikatika** [comment]
Hi heri16!

There are few functionalities that need to be implemented as native javascript functions/objects before we can merge the code to Espruino:

1. Incorporate a flash file system. We need to choose most suitable one, perhaps https://github.com/pellepl/spiffs
2. Socket + HTTP Web Server
3. FTP protocol for easy web scripts uploading (html, css, js - client/server side)
4. Web Socket as upgrade of HTTP protocol
5. Prepare python scripts for ESP8266 board for Espruino project

Any knowledge and experience in Espruino, NodeMCU, ESP8266 SDK and C/C++ programming as well as implementation of web technologies from above would come in handy.

Please let me know if you can help in any of these.
